set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR wasm)

set(CMAKE_C_COMPILER
  $ENV{EMSDK}/upstream/emscripten/emcc)

set(CMAKE_CXX_COMPILER
  $ENV{EMSDK}/upstream/emscripten/em++)

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)


set(CMAKE_IGNORE_PATH /opt/homebrew/lib /usr/lib /usr/local/lib CACHE STRING "")
